# Generated by Django 3.2.6 on 2021-08-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_auto_20210825_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.CharField(default='City', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='type',
            field=models.CharField(default='Country', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='type',
            field=models.CharField(default='Region', editable=False, max_length=50),
        ),
    ]
